package com.examly.springapp.service;

import com.examly.springapp.dto.CourseSearchRequest;
import com.examly.springapp.dto.PageResponse;
import com.examly.springapp.exception.DatabaseOperationException;
import com.examly.springapp.exception.InvalidRequestException;
import com.examly.springapp.exception.ResourceNotFoundException;
import com.examly.springapp.model.Cart;
import com.examly.springapp.model.Course;
import com.examly.springapp.model.Orders;
import com.examly.springapp.repository.CartRepo;
import com.examly.springapp.repository.CourseRepo;
import com.examly.springapp.repository.OrderRepo;
import com.examly.springapp.repository.ReviewRepo;
import java.util.List;
import java.util.Locale;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Course management rules (create, update, safe delete) and the course search.
 * Repository failures are wrapped into DatabaseOperationException.
 *
 * @author Sivamuthu
 * @author Amogh (search)
 */
@Service
public class CourseServiceImpl implements CourseService {
    private static final Logger log = LoggerFactory.getLogger(CourseServiceImpl.class);

    private final CourseRepo courseRepo;
    private final CartRepo cartRepo;
    private final OrderRepo orderRepo;
    private final ReviewRepo reviewRepo;

    public CourseServiceImpl(CourseRepo courseRepo, CartRepo cartRepo, OrderRepo orderRepo, ReviewRepo reviewRepo) {
        this.courseRepo = courseRepo;
        this.cartRepo = cartRepo;
        this.orderRepo = orderRepo;
        this.reviewRepo = reviewRepo;
    }

    @Override
    public Course addCourse(Course course) {
        log.trace("addCourse entered");
        course.setCourseId(null);   // the id is always generated by the database
        Course saved = DatabaseOperationException.guard("saving a course", () -> courseRepo.save(course));
        log.info("Course created with id {}", saved.getCourseId());
        return saved;
    }

    @Override
    public List<Course> getAllCourses() {
        log.trace("getAllCourses entered");
        List<Course> courses = DatabaseOperationException.guard("loading courses", () -> courseRepo.findAll());
        log.debug("getAllCourses returned {} course(s)", courses.size());
        return courses;
    }

    @Override
    public Course getCourseById(Long courseId) {
        log.trace("getCourseById entered for courseId={}", courseId);
        return DatabaseOperationException.guard("loading a course", () -> courseRepo.findById(courseId))
                .orElseThrow(() -> new ResourceNotFoundException("Course not found with id " + courseId));
    }

    @Override
    public Course updateCourse(Long courseId, Course course) {
        log.trace("updateCourse entered for courseId={}", courseId);
        Course existing = getCourseById(courseId);
        existing.setCourseType(course.getCourseType());
        existing.setCourseImageUrl(course.getCourseImageUrl());
        existing.setCourseDetails(course.getCourseDetails());
        existing.setCoursePrice(course.getCoursePrice());
        Course saved = DatabaseOperationException.guard("updating a course", () -> courseRepo.save(existing));
        log.info("Course {} updated", courseId);
        return saved;
    }

    @Override
    @Transactional
    public void deleteCourse(Long courseId) {
        log.trace("deleteCourse entered for courseId={}", courseId);
        Course course = getCourseById(courseId);

        // Business rule: detach the course from carts and orders first so foreign keys do not block the delete.
        List<Cart> carts = DatabaseOperationException.guard("loading carts", () -> cartRepo.findByCourses_CourseId(courseId));
        for (Cart cart : carts) {
            cart.getCourses().removeIf(c -> c.getCourseId().equals(courseId));
            cart.setTotalAmount(cart.getCourses().stream()
                    .mapToDouble(c -> c.getCoursePrice() == null ? 0 : c.getCoursePrice()).sum());
            DatabaseOperationException.guard("saving a cart", () -> cartRepo.save(cart));
        }

        List<Orders> orders = DatabaseOperationException.guard("loading orders", () -> orderRepo.findByCourses_CourseId(courseId));
        int emptied = 0;
        for (Orders order : orders) {
            order.getCourses().removeIf(c -> c.getCourseId().equals(courseId));
            if (order.getCourses().isEmpty()) {
                // an order with no course left is an old enrollment of a course that no longer exists
                DatabaseOperationException.guardVoid("deleting an order", () -> orderRepo.delete(order));
                emptied++;
            } else {
                DatabaseOperationException.guard("saving an order", () -> orderRepo.save(order));
            }
        }
        log.debug("deleteCourse: detached course {} from {} cart(s) and {} order(s), removed {} empty order(s)",
                courseId, carts.size(), orders.size(), emptied);

        String type = course.getCourseType();
        DatabaseOperationException.guardVoid("deleting a course", () -> courseRepo.delete(course));

        // Reviews are linked to a course by its type, so they go with the course
        // unless another course still uses that type.
        if (type != null && !DatabaseOperationException.guard("checking course types",
                () -> courseRepo.existsByCourseTypeIgnoreCase(type))) {
            long removed = DatabaseOperationException.guard("deleting reviews",
                    () -> reviewRepo.deleteBySubjectIgnoreCase(type));
            log.debug("deleteCourse: removed {} review(s) of '{}'", removed, type);
        }
        log.info("Course {} deleted", courseId);
    }

    /**
     * Search used by the course catalogue: keyword on type/details, optional price range, sorting and paging.
     *
     * @author Amogh
     */
    @Override
    public PageResponse<Course> searchCourses(CourseSearchRequest request) {
        log.trace("searchCourses entered");
        // Business rule: a missing bound means "no limit", so the query never has to deal with null parameters.
        double min = request.getMinPrice() == null ? 0.0 : request.getMinPrice();
        double max = request.getMaxPrice() == null ? Double.MAX_VALUE : request.getMaxPrice();
        if (min > max) {
            throw new InvalidRequestException("minPrice cannot be greater than maxPrice");
        }
        String pattern = likePattern(request.getKeyword());
        Pageable pageable = PageRequest.of(request.effectivePage(), request.effectiveSize(), sortFor(request.effectiveSort()));
        log.debug("searchCourses: pattern={}, min={}, max={}, sort={}, page={}, size={}",
                pattern, min, max, request.effectiveSort(), pageable.getPageNumber(), pageable.getPageSize());
        Page<Course> result = DatabaseOperationException.guard("searching courses",
                () -> courseRepo.search(pattern, min, max, pageable));
        log.debug("searchCourses returned {} of {} course(s)", result.getNumberOfElements(), result.getTotalElements());
        return PageResponse.from(result);
    }

    /**
     * Maps the public sort keyword to a Spring Sort. Unknown or missing values fall back to "newest".
     * The id is always the tie-breaker so paging is stable.
     *
     * @author Amogh
     */
    static Sort sortFor(String sort) {
        String key = sort == null ? CourseSearchRequest.DEFAULT_SORT : sort;
        Sort newestFirst = Sort.by(Sort.Direction.DESC, "courseId");
        switch (key) {
            case "priceAsc":
                return Sort.by(Sort.Direction.ASC, "coursePrice").and(newestFirst);
            case "priceDesc":
                return Sort.by(Sort.Direction.DESC, "coursePrice").and(newestFirst);
            case "name":
                return Sort.by(Sort.Direction.ASC, "courseType").and(newestFirst);
            default:
                return newestFirst;
        }
    }

    /**
     * Builds the lower-case SQL LIKE pattern for a keyword. '!' is the escape character, so the characters
     * ! % _ typed by a user are matched literally. A blank keyword matches everything.
     *
     * @author Amogh
     */
    static String likePattern(String keyword) {
        if (keyword == null || keyword.isBlank()) {
            return "%";
        }
        String escaped = keyword.trim().toLowerCase(Locale.ROOT)
                .replace("!", "!!")
                .replace("%", "!%")
                .replace("_", "!_");
        return "%" + escaped + "%";
    }
}